parameters:
#    bstu_user.example.class: Bstu\Bundle\UserBundle\Example

services:
   bstu_user.registration.form.type:
        class: Bstu\Bundle\UserBundle\Form\UserType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: bstu_bundle_userbundle_user }