bstu_test:
    resource: "@BstuTestBundle/Resources/config/routing.yml"
    prefix:   /student/

bstu_plan:
    resource: "@BstuPlanBundle/Resources/config/routing.yml"
    prefix:   /operator/

bstu_test_organization:
    resource: "@BstuTestOrganizationBundle/Resources/config/routing.yml"
    prefix:   /teacher/

bstu_user:
    resource: "@BstuUserBundle/Resources/config/routing.yml"
    prefix:   /

bstu_faculty:
    resource: "@BstuFacultyBundle/Resources/config/routing.yml"
    prefix:   /admin/
