<?php

namespace Bstu\Bundle\TestingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PulpitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PulpitRepository extends EntityRepository
{
}
