<?php

namespace Bstu\Bundle\TestOrganizationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends EntityRepository
{
    /**
     * Find all themes through subjects that relates to teacher
     *
     * @param \Bstu\Bundle\UserBundle\Entity\User $teacher
     * @return \Doctrine\Common\Collections\Collection
     */
    public function findAllByTeacher($teacher)
    {
        $qb = $this->createQueryBuilder('t')
            ->innerJoin('t.subject', 's')
            ->where('s.teacher = ?1')
            ->setParameter(1, $teacher)
            ->getQuery()
            ->getResult()
        ;
        return $qb;
    }
}
