<?php

namespace Bstu\Bundle\FacultyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FacultyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacultyRepository extends EntityRepository
{
}
