parameters:
    bstu_test_organization.testtype.class: Bstu\Bundle\TestOrganizationBundle\Form\TestType
    bstu_test_organization.resultquestiontype.class: Bstu\Bundle\TestOrganizationBundle\Form\ResultQuestionType
    bstu_test_organization.resulttesttype.class: Bstu\Bundle\TestOrganizationBundle\Form\ResultTestType
    
services:
    bstu_test_organization.testtype:
        class: %bstu_test_organization.testtype.class%
        arguments:
            - '@security.context'
        tags:
            - { name: form.type, alias: bstu_bundle_testorganizationbundle_test }
            
    bstu_test_organization.resultquestiontype:
        class: %bstu_test_organization.resultquestiontype.class%
        tags:
            - { name: form.type, alias: bstu_bundle_testorganizationbundle_resultquestion }
            
    bstu_test_organization.resulttesttype:
        class: %bstu_test_organization.resulttesttype.class%
        arguments:
            - '@router'
        tags:
            - { name: form.type, alias: bstu_bundle_testorganizationbundle_resulttest }
