parameters:
    bstu_test_organization.testtype.class: Bstu\Bundle\TestOrganizationBundle\Form\TestType

services:
    bstu_test_organization.testtype:
        class: %bstu_test_organization.testtype.class%
        arguments:
            - '@security.context'
        tags:
            - { name: form.type, alias: bstu_bundle_testorganizationbundle_test }
